border-width = 0
outline-width = 0
result-spacing = 10
num-results = 10
font = /usr/share/fonts/cantarell/Cantarell-VF.otf
prompt-text = ""
corner-radius = 10
width = 600
height = 550
text-cursor = true
padding-bottom = 10
padding-top = 10
padding-left = 10
padding-right = 10
placeholder-text = "Search"
placeholder-color = #fff4
selection-color = #ffff
selection-background = #fff4
selection-background-padding = 5
selection-background-corner-radius = 10
clip-to-padding = false